---
- name: Install Arc theme
  become: true
  when: ansible_os_family ==  "Debian"
  apt:
    name: arc-theme
    update_cache: yes
    state: latest

- name: Set desktop theme to Arc Dark
  command: xfconf-query -c xsettings -p /Net/ThemeName -s "Arc-Dark"

- name: Set window manager theme to Arc Darker
  command: xfconf-query -c xfwm4 -p /general/theme -s "Arc-Darker"

- name: Hide desktop icons
  command: "xfconf-query -c xfce4-desktop -np '/desktop-icons/style' -t 'int' -s '0'"

- name: Embiggen top panel
  command: xfconf-query --channel xfce4-panel -p /panels/panel-0/size -s 36

- name: Configure terminal settings
  copy:
    src: ../files/terminalrc
    dest: "{{ ansible_env.HOME }}/.config/xfce4/terminal/"
    force: no

- name: Create wallpaper directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/xfce4/backdrops"
    recurse: yes
    state: directory

- name: Implement suitably dystopian wallpaper
  copy:
    mode: 0600
    src: ../files/by_burned.jpg
    dest: "{{ ansible_env.HOME }}/.local/share/xfce4/backdrops/by_burned.jpg"

- name: Set wallpaper
  command: "xfconf-query --channel xfce4-desktop --property /backdrop/screen0/monitor0/workspace0/last-image --set {{ ansible_env.HOME }}/.local/share/xfce4/backdrops/by_burned.jpg"

# - name: Kill xfce4-panel
#   command: xfce4-panel --quit

# - name: Kill xfconfd
#   command: pkill xfconfd

- name: Remove all launchers
  file:
    state: absent
    path: "{{ ansible_env.HOME }}/.config/xfce4/panel"

- name: Create panel directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.config/xfce4/panel"

- name: Beam up Melon Cat
  copy:
    src: ../files/melon_cat.png
    dest: "{{ ansible_env.HOME }}/Pictures/melon_cat.png"
    mode: 0600
    force: yes
  register: meloncat

- name: Customize Whisker Menu
  when: meloncat.changed
  template:
    src: ../templates/whiskermenu-1.rc.j2
    dest: "{{ ansible_env.HOME }}/.config/xfce4/panel/whiskermenu-1.rc"
